### ISSUE TITLE
Refund is not available yet 

### ISSUE THREAD

**Issue by bigly2001** [tarassh/fairy-wallet#138]
![refund](https://user-images.githubusercontent.com/65622406/89820195-e1832380-db61-11ea-9285-0c45d8df0cba.png)
![refund2](https://user-images.githubusercontent.com/65622406/89820216-e942c800-db61-11ea-8677-4f43aca763ce.png)
![refund4](https://user-images.githubusercontent.com/65622406/89820706-ad5c3280-db62-11ea-95d5-75eeb957060c.png)

hi 
i delgate 20 eos (10 for cpu and 10 for ram)
but after undelgate it is still stacked and when i try to refund it says "Refund is not available yet" !!!
what can i do please help
thanks

**Comment by manuptmanupt** [comment]
I have same issue,  is this has been solved after 6 months?

**Comment by bigly2001** [comment]
Hi
No the problem not solved because nobody answered me
i never buy eos again

**Comment by stefano-p** [comment]
This project is dead. Ledger support states that they have no control over this wallet. Beware they have no control over the EOS app either!!!

**Comment by bigly2001** [comment]
Hi
no problem still exist.
damn to eos
